version: 0.2

phases:
  install:
    commands:
      - gem install bundler
      - gem install jekyll -v='4.2.2'
      - gem install minima
  pre_build:
    commands:
      - jekyll --version
      - bundler --version
  build:
    commands:
      - cd jfic-web
      - locale
      - export LC_CTYPE="utf-8"
      - bundle exec jekyll b
  post_build:
    commands:
      - cd _site
      - pwd
artifacts:
  files:
    - '**/*'
  name: jfic-jekyll-artifacts
  discard-paths: no
  base-directory: jfic-web/_site/
