version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.4
    commands:
      - gem install bundler -v '4.0.8'
      - cd jfic-web
      - bundle install --jobs 4 --retry 3
      - locale
      - locale -a
      - export LC_CTYPE="C.utf8"      
  pre_build:
    commands:
      - bundler --version
      - bundle exec jekyll --version
  build:
    commands:    
      - bundle exec jekyll build
  post_build:
    commands:
      - cd _site
      - pwd
artifacts:
  files:
    - '**/*'
  name: jfic-jekyll-artifacts
  discard-paths: no
  base-directory: jfic-web/_site/
